includes("check_cincludes.lua")
set_version("2.4")
set_project("buddy")

configvar_check_cincludes("HAVE_DLFCN_H","dlfcn.h")
configvar_check_cincludes("HAVE_INTTYPES_H","inttypes.h")
configvar_check_cincludes("HAVE_MEMORY_H","memory.h")
configvar_check_cincludes("HAVE_STDINT_H","stdint.h")
configvar_check_cincludes("HAVE_STDLIB_H","stdlib.h")
configvar_check_cincludes("HAVE_STRINGS_H","strings.h")
configvar_check_cincludes("HAVE_STRING_H","string.h")
configvar_check_cincludes("HAVE_SYS_STAT_H","sys/stat.h")
configvar_check_cincludes("HAVE_SYS_TYPES_H","sys/types.h")
configvar_check_cincludes("HAVE_UNISTD_H","unistd.h")
configvar_check_cincludes("STDC_HEADERS",{"stdlib.h","stdarg.h","string.h","float.h"})
set_configdir("src/")
add_cxflags("-fno-stack-protector","")
add_configfiles("config.h.in")
add_includedirs("src")
includes({"src/xmake.lua","examples/xmake.lua"})

